AWS_ACCESS_KEY_ID = 'DO00ZZ7NGQE8QH2BVMY9' #KEY_ID HERE
AWS_SECRET_ACCESS_KEY = 'tl5jL+AtPn8Q4yKLkisJSx3FX/fonZC5bGAfUSpPF7Q' #ACCESS_KEY HERE

AWS_ROOT = 'https://nyc3.digitaloceanspaces.com' #Example
AWS_STORAGE_BUCKET_NAME = 'mlsm-a' #Bucket Name Here