# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-08-06 08:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('brokerage', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked', models.NullBooleanField()),
                ('bathrooms', models.SmallIntegerField(null=True)),
                ('bathrooms_plus', models.SmallIntegerField(null=True)),
                ('bedrooms', models.SmallIntegerField(null=True)),
                ('bedrooms_plus', models.SmallIntegerField(null=True)),
                ('kitchens', models.TextField(blank=True)),
                ('kitchens_plus', models.TextField(blank=True)),
                ('washrooms', models.TextField(blank=True)),
                ('washrooms_plus', models.TextField(blank=True)),
                ('style', models.TextField(blank=True)),
                ('approx_age', models.TextField(blank=True)),
                ('square_ft', models.TextField(blank=True)),
                ('garage_type', models.TextField(blank=True)),
                ('garage_spaces', models.TextField(blank=True)),
                ('parking_spaces', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreage', models.TextField(blank=True)),
                ('access_type', models.TextField(blank=True)),
                ('zoning', models.TextField(blank=True)),
                ('lot_depth', models.TextField(blank=True)),
                ('lot_length', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(null=True)),
                ('created_at', models.TextField(blank=True)),
                ('last_updated', models.TextField(null=True)),
                ('mls', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('extra_description', models.TextField(null=True)),
                ('possession_notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fronting_on', models.TextField(null=True)),
                ('full_address', models.TextField(null=True)),
                ('street_name', models.TextField(null=True)),
                ('street_number', models.TextField(null=True)),
                ('street_abbrev', models.TextField(null=True)),
                ('street_direction', models.TextField(null=True)),
                ('apt_num', models.TextField(null=True)),
                ('province', models.TextField(null=True)),
                ('postal_code', models.TextField(null=True)),
                ('area', models.TextField(null=True)),
                ('municipality', models.TextField(null=True)),
                ('community', models.TextField(null=True)),
                ('district', models.TextField(null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.SmallIntegerField()),
                ('path', models.TextField(blank=True)),
                ('identifier', models.TextField(blank=True)),
                ('mime_type', models.TextField(blank=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.TextField(null=True)),
                ('length', models.TextField(null=True)),
                ('level', models.TextField(null=True)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Washroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.TextField(null=True)),
                ('level', models.TextField(null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Source'),
        ),
        migrations.AddField(
            model_name='land',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.Listing'),
        ),
        migrations.AddField(
            model_name='building',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Listing'),
        ),
        migrations.AddField(
            model_name='agent',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.Listing'),
        ),
    ]
