# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-08-07 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='media_updated',
            field=models.BooleanField(default=False),
        ),
    ]
