# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-08-07 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_listing_media_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='media_updated',
        ),
        migrations.AddField(
            model_name='listing',
            name='media_ingested_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='media_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
