# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-08-07 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20230807_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='media_ingested_at',
        ),
        migrations.AddField(
            model_name='listing',
            name='media_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='media_updated_at',
            field=models.TextField(null=True),
        ),
    ]
